### ISSUE TITLE
Link not working 

### ISSUE THREAD

**Issue by michael-rpi** [raspberrypilearning/moonhack-scratch#2]
Although the link to the Scratch guide in step 1 works from GitHub, on the live site it links to https://codeclubprojects.org/en-GB/https://projects-static.raspberrypi.org/projects/moonhack-scratch/e09b802ee04a22932cde4a67e5b7b429b357bd7b/en/resources/scratch-intro/ , which gives a 404 error.

**Comment by MarcScott** [comment]
I've added an issue on the projects ui site, as I can't see an issue here - https://github.com/RaspberryPiFoundation/projects-ui/issues/1171
